feat(asteroids): add asteroids subject
Coding-Club-Lab-Lyon/Sujets pull request #8
Opened 2024-04-27 02:07 UTC by Mael-RABOT

- 7h subject for a high school
- Main theme:
    - OOP
- tkinter

2024-04-27 07:58 UTC, YohannMgt requested changes

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +- Même si le sujet temps à être accessible, il est préférable d'avoir déjà une première expérience en programmation.
typo: tend

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +- Consolider tes acquis en python
python -> Python

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Le sujet peut sembler ne pas vous donner beaucoup d'instructions, car votre objectif est de faire les recherches nécessaires pour comprendre le code et mettre en œuvre la logique du jeu par vous même
vous même -> vous-même

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Tout au long du sujet, les parties de code à complétées seront indiquées par des commentaires `# TODO`.<br>
compléter

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +>:info Naviguer dans un termial<br>Si tu utilise un terminal, les commandes suivantes peuvent t'aider à naviguer dans les dossiers:<br>- `ls` : lister les fichiers et dossiers<br>- `cd ..` : remonter
ou qu'est ce que tu es -> où est-ce que tu es

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +En paralèlle de cett définition, l'OOP apporte plusieurs concepts:
cett -> cette

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +En paralèlle de cett définition, l'OOP apporte plusieurs concepts:
paralèlle -> parallèle

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +La plupart des ces concepts étant difficile à comprendre et à mettre en place, ils ne seront que très peu abordés dans ce projet.<br>
des -> de

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Le fichier `Vector2D.py` contient la base d'une classe `Vector2D` qui représente un vecteur à deux dimension, x & y.<br>
dimension -> dimensions

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Maintenant que la base du projet est réparée, tu es pret à passer aux choses sérieuses.<br>
pret -> prêt

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Chaque fonctions possèdes des instructions qui te guideront dans la réparation du jeu.<br>
fonctions possèdes -> fonction possède

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Mais après avoir jouer un peu, tu as du te rendre compte que le jeu est un peu... vide.<br>
jouer -> joué

2024-04-27 07:58 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Mais après avoir jouer un peu, tu as du te rendre compte que le jeu est un peu... vide.<br>
du -> dû

2024-04-27 10:41 UTC, YohannMgt requested changes

2024-04-27 10:41 UTC, YohannMgt commented on Asteroids/subject/Asteroids.md
> +Chaque fonctions possède des instructions qui te guideront dans la réparation du jeu.<br>
fonctions -> fonction

2024-04-29 07:55 UTC, YohannMgt approved these changes

2024-04-29 10:51 UTC, merged

2024-04-29 10:52 UTC, Nellypal reviewed
chiengues (ok)